Proyecto-B/errorPages/categoria/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('registrar/', registrar_categoria, name='registrar_categoria'),
    path('api/get', lista_categoria, name='lista_categoria'),
    path('json/', json_categoria, name='json_categoria'),
    path('api/post/', agregar_categoria, name='post')
]

Proyecto-B/errorPages/errorPages/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('error/', generar_error, name='error'),
    path('onepage/', onepage, name='onepage'),
    path('prueba/', prueba_front, name='prueba'),
    path('search/', search_view, name='search'),
    path('error_logs/', error_logs, name='error_logs'),
    path('api/error_logs/', get_error_logs, name='get_error_logs'),
    path('users/', include('users.urls')),
    path('productos/', include('productos.urls')),
    path('categoria/', include('categoria.urls')),
    path('alumnos/', include('alumnos.urls')),
]

Proyecto-B/errorPages/users/urls.py
from django.urls import path, include
from .views import *
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import TokenRefreshView

router = SimpleRouter()
router.register(r'api', UserViewSets)

urlpatterns = [
    path('', include(router.urls)),
    #Este es el path para iniciar sesion <-- Requiere email y password (POST)
    path('token/', CustomTokenObtainPairView.as_view(), name='token'),
    path('token/refresh/', TokenRefreshView.as_view(), name='refresh'), 
    path('form/', CustomUserFormAPI.as_view(), name='user_form_api'),
]

Proyecto-B/errorPages/categoria/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    # atributos de clase
    nombre = models.CharField(max_length=100)
    imagen = models.URLField()
    
    def __str__(self):
        return self.nombre
    
    # Necesito una funcion que devuelva el objeto en forma de Dict
    
    def to_dict(self):
        return {
            # 'ClaveValor': 'Valor'
            'nombre': self.nombre,
            'imagen': self.imagen
        }

Proyecto-B/errorPages/categoria/forms.py
# Generar todos los formularios HTML que vamos a ocupar
from django import forms
from .models import Categoria

# Crear una clase para cada formulario que necesitemos
class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        # que campos van a verse en mi formulario
        fields = ['nombre', 'imagen']
        
        # Personalizar inputs
        widgets = {
            'nombre': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nombre de la categoría'
                }),
            'imagen': forms.URLInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'URL de la imagen'
                })
        }
        
        # Etiquetas
        labels = {
            'nombre': 'Nombre de la categoría',
            'imagen': 'URL de la imagen'
        }
        
        # Personalizar los mensajes de error
        error_messages = {
            'nombre': {
                'required': 'Este campo es obligatorio'
            },
            'imagen': {
                'required': 'Este campo es obligatorio'
            }
        }

Proyecto-B/errorPages/categoria/views.py
from django.shortcuts import render, redirect
from .models import Categoria
from django.http import JsonResponse

from .forms import CategoriaForm

# vista que carga y muestra el formulario
def registrar_categoria(request):
    # checar si vengo del formulario
    if request.method == 'POST':
        # quiere decir que enviaron el form
        form = CategoriaForm(request.POST)
        # checar que sus datos esten bien
        if form.is_valid():
            form.save()
            return redirect('json_categoria')
    # Que pasa si no fue que mandaron el form
    else:
        form = CategoriaForm()
    return render(request, 'registrar.html', {'form': form})

# Vista que devuelve las categorias como JSON
def lista_categoria(request):
    # Obtener todas las categorias de la base de datos
    categorias = Categoria.objects.all()
    
    # vamos a guardar los datos en un dict
    # este diccionario fue creado al aire y no es seguro
    data = [
        {
            'nombre': c.nombre,
            'imagen': c.imagen
        }
        for c in categorias
    ]
    
    return JsonResponse(data, safe=False)

def json_categoria(request):
    return render(request, 'json.html')

import json

# Funcion que agrega un categoria con un objeto json
def agregar_categoria(request):
    if request.method == 'POST':
        #quiere decir que si estoy manejando el request
        try:
            data = json.loads(request.body)
            categoria = Categoria.objects.create(
                nombre = data['nombre'],
                imagen = data['imagen']
            )
            return JsonResponse({
                'mensaje': 'Registro Exitoso',
                'id': categoria.id
            }, status=201)
        except Exception as e:
            print(str(e))
            return JsonResponse({
                'error': str(e)
            }, status=400)
    return JsonResponse({
        'error': 'El metodo no esta doportado'
    }, status=405)
    

Proyecto-B/errorPages/categoria/templates/json.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categorías</title>
    <!-- Agregar Bootstrap 5 desde CDN -->  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        .card-img-top {
            object-fit: cover;
            height: 400px;
        }
    </style>
</head>
<body class="bg-light">
    <div class="container mt-5">
        <h1 class="text-center mb-4">Categorias</h1>
        <div class="row" id="categoria-container">
        </div>
    </div>
    <script>
        fetch('/categoria/api/get')
            .then(response => response.json())
            .then(data => {
                const categoriaContainer = document.getElementById('categoria-container');
                
                categoriaContainer.innerHTML = '';

                data.forEach(categoria => {
                    const cardHTML = `
                        <div class="col-md-4 mb-4">
                            <div class="card shadow-sm">
                                <img src="${categoria.imagen}" class="card-img-top img-fluid" alt="Imagen de la categoría">
                                <div class="card-body">
                                    <h5 class="card-title">${categoria.nombre}</h5>
                                </div>
                            </div>
                        </div>
                    `;
                    categoriaContainer.innerHTML += cardHTML;
                });
            })
            .catch(error => {
                console.error("Error al cargar las categorias:", error);
            });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
</body>
</html>

Proyecto-B/errorPages/categoria/templates/registrar.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Categoria</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .card-img-top {
            object-fit: cover;
            height: 100px;
        }
    </style>
</head>
<body class="bg-light">

    <div class='container'>
        <div class='col'>
          <div class='row'>
            <!-- FORM -->
            <div class="col-6 mt-4">
                <h1 class="text-center mb-4">Registrar Nueva Categoria</h1>
                <form method="post" id='categoriaForm'>
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_nombre" class="form-label">Nombre de la Categoria</label>
                    {{ form.nombre }}
                    {% if form.nombre.errors %}
                        <div class="text-danger">
                            {% for error in form.nombre.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
    
                <div class="mb-3">
                    <label for="id_imagen" class="form-label">URL de la imagen</label>
                    {{ form.imagen }}
                    {% if form.imagen.errors %}
                        <div class="text-danger">
                            {% for error in form.imagen.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="d-flex justify-content-between">
                    <a href="{% url 'json_categoria' %}" class="btn btn-secondary">Volver</a>
                    <button type="submit" class="btn btn-primary">Registrar Categoria</button>
                </div>
                </form>
            </div>
            <!-- Vista -->
            <div class="col-6 mt-4">
                <h1>Vista de categorias</h1>
                <div class="row" id="categorias"></div> 
               </div>
          </div>
        </div>
    </div>

    <div class="container mt-5">
    
    
        <p id="mensaje"></p>
      </div>
      <script>
        var form = document.getElementById('categoriaForm');
        form.addEventListener('submit', function(event){
          //Que bi se va a mandar el form a la vista que hace render
          event.preventDefault();
          //necesito informacion
          let formData = new FormData(this);
    
          //convertir el formData en Json
          let jsonData = {};
          //en este contexto el value es el valor del input y el key es el name del input
          formData.forEach((value, key) => jsonData[key] = value);
          //'nombre' : 'peluche pikachu'
          
          //Enviar esta info al endpoint con post
          fetch('/categoria/api/post/', {
            method: 'POST', 
            headers: {
              'Content-Type': 'application/json',
              'X-CSRFToken': getToken() //WIP
            },
            body: JSON.stringify(jsonData) 
          })
          .then(response => response.json())
          .then(data => {
            document.getElementById('mensaje').innerText = data.mensaje;
            //cargar los categoria
            cargarCategoria();
          })
          .catch(error => console.error('Error:', error));
        });
    
        //Funcion para obtener el CSRFToken en js
        function getToken(){
          let cookieValue = null;
          let cookies = document.cookie.split(';');
          for(let i = 0; i < cookies.length; i++){
            let cookie = cookies[i].trim();
            if(cookie.startsWith('csrftoken=')){
              cookieValue = cookie.substring("csrftoken=".length, cookie.length)
              break;
            }
          }
          return cookieValue;
        }
      </script>
      <script>
        function cargarCategoria() {
            fetch('/categoria/api/get')
            .then(response => response.json())
            .then(data => {
                let categoriaDiv = document.getElementById('categorias');
                categoriaDiv.innerHTML = ''; // Limpiar contenido antes de agregar nuevos
    
                data.forEach(categoria => {
                    categoriaDiv.innerHTML += `
                        <div class="col-md-4 mb-4">
                            <div class="card shadow-sm">
                                <img src="${categoria.imagen}" class="card-img-top img-fluid" alt="${categoria.nombre}">
                                <div class="card-body text-center">
                                    <h5 class="card-title">${categoria.nombre}</h5>
                                </div>
                            </div>
                        </div>`;
                });
            })
            .catch(error => console.error('Error:', error));
        }
    
        cargarCategoria();
      </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
</body>
</html>